### ISSUE TITLE
[Bug]: React Context not persisting across client side page transitions. App router.

### ISSUE THREAD

**Issue by ehowey** [netlify/next-runtime#2402] opened 2023-12-27 16:51 UTC
### Summary

Hello!

I am running into an issue with React Context not persisting properly across page transitions when using the app router. It works in local dev, works on Vercel, but the context/state is resetting on each page transition with Netlify. Note this bug is only present when deployed, so tricky to debug and fix.  The minimal reproduction is below.

Site on Netlify: https://nextjs-netlify-context-bug.netlify.app/
Site on Vercel: https://nextjs-netlify-context-bug.vercel.app/

### A link to a reproduction repository

https://github.com/ehowey/context-bug

### Expected Result

React context works properly and state is persisted across page transitions.

### Actual Result

React context is resetting state on page transitions

### Steps to reproduce

1. Clone repo
2. Deploy to Netlify

### Next Runtime version

4.41.3

### Is your issue related to the `app` directory?

- [X] Yes, I am using the `app` directory

### Build information

I used all of the default build settings and let Netlify autodetect NextJs.

**Comment by Christopotamus** [comment] 2024-01-12 23:02
This looks like it's a result of this bug https://github.com/netlify/next-runtime/issues/2089 to me. I see a full page reload happening when navigating between pages on Netlify but not on Vercel.

**Comment by ehowey** [comment] 2024-01-13 00:01
Yep that looks like it to me too. I'm surprised this isn't taking a bigger focus as it seems like a fairly major issue.

**Comment by mysterybear** [comment] 2024-02-02 09:34
We are experiencing the same thing, is there any chance of this being fixed any time soon?

**Comment by serhalp** [comment] 2024-06-04 16:39
Duplicate of #2089

**Closed by serhalp** 2024-06-04 16:39 UTC
Labels: type: bug, v4
